### ISSUE TITLE
Yarn Start 

### ISSUE THREAD

**Issue by till-valhaalla** [miyabi-satoh/canvas-editor#21]
Unable to run on local server please help 
![Error](https://user-images.githubusercontent.com/86537855/154014423-bcd7ebb6-96d4-4ed2-8284-84b48ce893ef.PNG)

**Comment by miyabi-satoh** [comment]
Please confirm your Node.js version.
node-sass runs under Node.js v12 or less than.
See Supported Environments.
https://github.com/sass/node-sass/releases/tag/v4.12.0

(I'm sorry for my poor English.)

**Comment by till-valhaalla** [comment]
Hey! Thanks the issue is resolved 
but the images for background & Add Decoration is not working and they are not clickable
![image](https://user-images.githubusercontent.com/86537855/154202706-13008470-9fca-40c7-90f2-79075dac6d8f.png)

**Comment by miyabi-satoh** [comment]
What image is that?
When this project runs(yarn run dev), browser shows the page like this image.
![localhost_3000](https://user-images.githubusercontent.com/6127007/154393702-fcc15ffd-40b4-4c0c-8b39-06fd2ce6147f.png)

**Comment by till-valhaalla** [comment]
Ah I am sorry! i ran the different project now it is working perfectly fine thankyou! :) 
![image](https://user-images.githubusercontent.com/86537855/154406854-e4d041b9-7448-4a6d-a2cd-2ed1712b315d.png)

**Comment by till-valhaalla** [comment]
This is amazing keep up the awesome work!

**Comment by miyabi-satoh** [comment]
Good luck & hack!
